name: deploy-api
on:
  push:
    branches:
      - master
    paths:
      - 'packages/shared/**'
      - 'packages/api/**'
      - '.github/**'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: c-hive/gha-yarn-cache@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create a dotenv file
        run: |
          cat << EOF > ./packages/api/.env
          ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }}
          KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
          EOF
      - uses: serverless/github-action@master
        with:
          args: deploy
        working-directory: ./packages/api
