name: deploy-web
on:
  push:
    branches:
      - master
    paths:
      - 'packages/shared/**'
      - 'packages/web/**'
      - '.github/workflows/web-deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create a dotenv file
        run: |
          cat << EOF > ./packages/web/.env
          REACT_APP_KAKAO_MAP_API_KEY=${{ secrets.REACT_APP_KAKAO_MAP_API_KEY }}
          REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}
          EOF
      - uses: aws-actions/configure-aws-credentials@v1
        name: Setup AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: c-hive/gha-yarn-cache@v2
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.3.0
        name: Build React project
        with:
          cmd: workspace @dorobo/web build
      - name: Deploy to S3
        run:
          aws s3 sync ./packages/web/build ${{ secrets.S3_BUCKET_URI }}
      - name: Invalidate Cloudfront cache
        run:
          aws cloudfront create-invalidation --distribution-id ${{ secrets.S3_DISTRIBUTION_ID }} --paths "/*"
